<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7gM19ha\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7gM19ha/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7gM19ha.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7gM19ha\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7gM19ha\appAppKernelProdContainer([
    'container.build_hash' => '7gM19ha',
    'container.build_id' => '8de2dda9',
    'container.build_time' => 1734720301,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7gM19ha');
